spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3308/daretMilionnaire?createDatabaseIfNotExist=true
    username: root
    password: "1234567890"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  mail:
    host: localhost
    port: 9025

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    lease-renewal-interval-in-seconds: 30   # fréquence des heartbeats
    lease-expiration-duration-in-seconds: 90 # temps d’expiration

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

